import "./FinalReport.css";
import { useNavigate } from "react-router-dom";

function FinalReport() {
  const navigate = useNavigate();

  const report = `
==============================
      LAUNCHMATE AI REPORT
==============================

1. Startup Summary
AI Study Planner
Education
Freemium

2. Market Research
High Demand
Students

3. Business Plan
Subscription Model
Premium Plan

4. Finance
₹2,50,000
Break-even: 8 Months

5. Marketing Strategy
Instagram
YouTube

6. Legal & Compliance
GST Registration
MSME Registration

7. AI Mentor Advice
Start with student community.
Focus on low-cost marketing.

==============================
       END OF REPORT
==============================
`;

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = async () => {
    try {
      const response = await fetch(
        "http://127.0.0.1:8000/download-report",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            report: report,
          }),
        }
      );

      if (!response.ok) {
        alert("Failed to generate PDF");
        return;
      }

      const blob = await response.blob();

      const url = window.URL.createObjectURL(blob);

      const a = document.createElement("a");
      a.href = url;
      a.download = "startup_report.pdf";
      document.body.appendChild(a);
      a.click();
      a.remove();

      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error(error);
      alert("Download failed");
    }
  };

  return (
    <div className="report-container">
      <div className="navigation-buttons">
        <button
          className="back-btn"
          onClick={() => navigate("/legal")}
        >
          ◀
        </button>
      </div>

      <h1>Final Report</h1>

      <div className="top-card">
        <h2>📄 Your Startup Plan is Ready!</h2>
        <p>
          Here is the completed summary of your startup plan generated by
          LaunchMate AI.
        </p>
        <small>📅 Generated on: 18 July</small>
      </div>

      <div className="result-card">
        <h3>1. Startup Summary</h3>
        <p>• AI Study Planner</p>
        <p>• Education</p>
        <p>• Freemium</p>
      </div>

      <div className="result-card">
        <h3>2. Market Research</h3>
        <p>• High Demand</p>
        <p>• Students</p>
      </div>

      <div className="result-card">
        <h3>3. Business Plan</h3>
        <p>• Subscription Model</p>
        <p>• Premium Plan</p>
      </div>

      <div className="result-card">
        <h3>4. Finance</h3>
        <p>• ₹2,50,000</p>
        <p>• Break-even: 8 Months</p>
      </div>

      <div className="result-card">
        <h3>5. Marketing Strategy</h3>
        <p>• Instagram</p>
        <p>• YouTube</p>
      </div>

      <div className="result-card">
        <h3>6. Legal & Compliance</h3>
        <p>• GST Registration</p>
        <p>• MSME Registration</p>
      </div>

      <div className="result-card">
        <h3>7. AI Mentor Advice</h3>
        <p>• Start with student community.</p>
        <p>• Focus on low-cost marketing.</p>
      </div>

      <div className="button-group">
        <button
          className="download-btn"
          onClick={handleDownload}
        >
          ⬇ Download PDF
        </button>

        <button
          className="print-btn"
          onClick={handlePrint}
        >
          🖨 Print Report
        </button>
      </div>
    </div>
  );
}

export default FinalReport;